### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by Thandohimself** [Kristina-Simakova/arfaces#4]

**Comment by Majidalichoudhary** [comment]
> Hey Kristina, awesome repo, best I have seen for ARcore.
> 
> I'm creating a necklace try-on for android, I have already coded it in c++ with the power of openCV.
> 
> ![t](https://user-images.githubusercontent.com/25416573/80661481-1675d980-8a8f-11ea-93e3-f8facd7d6af8.png)
> ![Screenshot 2020-03-09 at 12 29 13 copy](https://user-images.githubusercontent.com/25416573/80661493-1d045100-8a8f-11ea-800f-880773f59c82.png)
> 
> I want to tryout ARcore after reading your [blog](https://t.co/SbrpHnRYIi?amp=1) and code it for android devices.
> I understand that I will have to create models in Blender. but now how will I position the necklace model on my neck?
> 
> How would you tackle this use-case Kristina?

hey did you get any solution how to detect neck for arcore and try out jewlry necklace?
